atividade 21/06/2022 - APEX VARIÁVEIS E OPERADORES
//1. Escreva um algoritmo que defina  um valor inteiro e escreva na tela seu valor.
integer valor = 2;
system.debug(valor);

---------------------------------------------------------------------------------
//2. Escreva um algoritmo que tenha nome de produto e preço exiba na tela os valores.7
string produto1 = 'fanta';
decimal valorproduto1 = 10.00;
system.debug(produto1 + ' custa R$ ' + valorproduto1);
 
---------------------------------------------------------------------------------
//3. Escreva um algoritmo que defina um valor inteiro e escreva (na tela) o seu antecessor. 
integer a = 2;
system.debug('a = ' + a--);
system.debug('a - 1 = ' + a);

-----------------------------------------------------------------------------------
//4. Escreva um algoritmo que tenha dois valores reais, some os valores e exiba o resultado.
integer a = 2;
integer b = 3;
integer c = 5;
integer s = a + b + c;
system.debug('a = ' + a);
system.debug('b = ' + b);
system.debug('c = ' + c)
system.debug('a + b + c = ' + s);

------------------------------------------------------------------
//5. Escreva um algoritmo que receba uma idade, subtraia do ano atual e exiba o resultado, mostrando ‘Nascido em (valorDaSubtração)’.
integer Idade = 30;
integer AnoAtual = 2022;
integer AnoNascimento = Anoatual - Idade;
system.debug('Idade' + Idade);
system.debug('Nascido em ' + AnoNascimento);

----------------------------------------------------------------
//6. Escreva um algoritmo para definir as dimensões de um retângulo (base e altura), calcular e escrever a área do retângulo.
integer C = 20;
integer A = 5;
integer area = C * A;
system.debug('Comprimento do retângulo ' + C + 'm');
system.debug('Altura do retângulo ' + A + 'm');
system.debug('Área do retângulo ' + area + 'm²');

--------------------------------------------------------------
//7. Escreva um algoritmo para definir o salário mensal atual de um funcionário e o percentual de reajuste de 25%. Calcular e escrever o valor do novo salário com o acréscimo do reajuste.
decimal Salario = 3000.00;
decimal Reajuste = 125;
decimal SalarioReajustado = (Salario/100) * Reajuste;
system.debug('Salário base = R$ ' + Salario);
system.debug('Reajuste de 25%');
system.debug('Salário reajustado = R$ ' + SalarioReajustado);

----------------------------------------------------------
//8. Escreva um algoritmo que atribua 3 notas, calcule a média e exiba o resultado.
integer av1 = 10;
integer av2 = 9;
integer av3 = 8;
integer media = (av1 + av2 + av3)/3;
system.debug('nota av1 ' + av1);
system.debug('nota av2 ' + av2);
system.debug('nota av3 ' + av3);
system.debug('média ' + media);

-----------------------------------------------------------
//9. Faça um algoritmo que define três notas de um aluno, calcule e escreva a média final deste aluno. Considerar que a média é ponderada e que o peso das notas é 2, 3 e 5. Fórmula para o cálculo da média final é:
integer av1 = 7;
integer av2 = 10;
integer av3 = 8;
integer media = ((av1 * 2) + (av2 * 3) + (av3 * 5)) /10;
system.debug('nota av1 = ' + av1);
system.debug('nota av2 = ' + av2);
system.debug('nota av3 = ' + av3);
system.debug('média ponderada = ' + media);

--------------------------------------------------------------
//Atividade em sala IF
//Crie uma variável string com um nome qualquer armazenado, verifique se o nome é Romero.
//Se for verdade escreva Romero Brito? Adriano?
//Se não imprima faz isso comigo não vei!
string nome1 = 'Romero Brito';
string nome2 = 'romero brito';
string nome3 = 'romerinho brita';
string nome4 = 'Romerão Pedreiro';

if(nome1 == ('Romero Brito')){
    System.debug('Romero Brito? Adriano?');}
else{System.debug('Faz isso comigo não vei!');}

if(nome2 == ('Romero Brito')){
    System.debug('Romero Brito? Adriano?');}
else{System.debug('Faz isso comigo não vei!');}

if(nome3 == ('Romero Brito')){
    System.debug('Romero Brito? Adriano?');}
else{System.debug('Faz isso comigo não vei!');}

if(nome4 == ('Romero Brito')){
    System.debug('Romero Brito? Adriano?');}
else{System.debug('Faz isso comigo não vei!');}

------------------------------------------------------------------------------------

string nome1 = 'Romero Brito';
string nome2 = 'romero brito';
string nome3 = 'romerinho brita';
string nome4 = 'Romerão Pedreiro';


